import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { mkdtemp } from "node:fs/promises";
import Database from "better-sqlite3";
import { validateAgentActivityV1 } from "../dist/core/validation/agent-orchestration/index.js";
import { prepareKitSqliteDatabase } from "../dist/core/state/workspace-kit-sqlite.js";
import { agentActivityLeaseToDashboardStatus, agentActivityLeaseToV1, clearAgentActivityLeases, deriveAgentActivityLifecycle, heartbeatAgentActivityLease, listCurrentAgentActivityLeases, readCurrentAgentActivityLease, setAgentActivityLease } from "../dist/modules/task-engine/agent-activity-store.js";
async function openDb(){const w=await mkdtemp(path.join(os.tmpdir(),"wk-agent-activity-"));const db=new Database(path.join(w,"workspace-kit.db"));prepareKitSqliteDatabase(db);return db;}
function seedTaskRow(db,taskId){const now="2026-05-31T08:00:00.000Z";db.prepare(`INSERT INTO task_engine_tasks (id, status, type, title, created_at, updated_at, archived, depends_on_json) VALUES (?, 'ready', 'workspace-kit', 'fixture', ?, ?, 0, '[]')`).run(taskId,now,now);}
test("agent activity leases set, heartbeat, clear, and project to dashboard status", async()=>{const db=await openDb();try{setAgentActivityLease(db,{activityId:"copilot:session-1",agentId:"copilot",sessionId:"session-1",kind:"working_task",label:"Working on Task T100",phaseKey:"81",now:"2026-05-06T10:00:00.000Z",expiresAt:"2026-05-06T10:05:00.000Z",details:{detail:"from test"}});assert.equal(readCurrentAgentActivityLease(db,"2026-05-06T10:01:00.000Z")?.label,"Working on Task T100");const heartbeat=heartbeatAgentActivityLease(db,{activityId:"copilot:session-1",now:"2026-05-06T10:02:00.000Z",expiresAt:"2026-05-06T10:07:00.000Z"});assert.equal(agentActivityLeaseToDashboardStatus(heartbeat,"2026-05-06T10:02:00.000Z").confidence,"high");assert.equal(clearAgentActivityLeases(db,{agentId:"copilot",sessionId:"session-1"}),1);}finally{db.close();}});
test("deriveAgentActivityLifecycle uses A-ACTIVITY 30s and 60s thresholds",()=>{const lease={updatedAt:"2026-05-31T08:30:00.000Z",expiresAt:"2026-05-31T08:31:30.000Z"};assert.equal(deriveAgentActivityLifecycle(lease,"2026-05-31T08:30:30.000Z"),"fresh");assert.equal(deriveAgentActivityLifecycle(lease,"2026-05-31T08:30:30.001Z"),"aging");assert.equal(deriveAgentActivityLifecycle(lease,"2026-05-31T08:31:00.001Z"),"stale");assert.equal(deriveAgentActivityLifecycle(lease,"2026-05-31T08:31:30.000Z"),"expired");});
test("agent activity v1 fixture validates and persists with task FK seed", async()=>{const db=await openDb();try{const fixture=JSON.parse(await readFile(path.join(process.cwd(),"fixtures/agent-orchestration/agent-activity-working-task.v1.json"),"utf8"));assert.equal(validateAgentActivityV1(fixture).ok,true);seedTaskRow(db,fixture.taskId);const lease=setAgentActivityLease(db,{activityId:fixture.activityId,agentId:fixture.agentId,sessionId:fixture.sessionId,agentDefinitionId:fixture.agentDefinitionId,assignmentId:fixture.assignmentId,kind:fixture.kind,label:fixture.label,currentStep:fixture.currentStep,command:fixture.command,hostHint:fixture.hostHint,modelTier:fixture.modelTier,modelHint:fixture.modelHint,thinkingLevel:fixture.thinkingLevel,taskId:fixture.taskId,phaseKey:fixture.phaseKey,now:fixture.updatedAt,expiresAt:fixture.expiresAt,details:fixture.details??null});assert.equal(lease.thinkingLevel,fixture.thinkingLevel);assert.equal(validateAgentActivityV1(agentActivityLeaseToV1(lease)).ok,true);}finally{db.close();}});
test("stale leases stay visible until expiry with low dashboard confidence", async()=>{const db=await openDb();try{setAgentActivityLease(db,{activityId:"stale-visible",agentId:"worker",sessionId:"default",kind:"working_task",label:"Still listed while stale",now:"2026-05-31T08:30:00.000Z",expiresAt:"2026-05-31T08:32:00.000Z"});const now="2026-05-31T08:31:05.000Z";assert.equal(listCurrentAgentActivityLeases(db,now).length,1);assert.equal(agentActivityLeaseToDashboardStatus(listCurrentAgentActivityLeases(db,now)[0],now).confidence,"low");}finally{db.close();}});
test("agent activity leases expire and ignore unknown or corrupt rows", async()=>{const db=await openDb();try{setAgentActivityLease(db,{activityId:"expired",agentId:"copilot",sessionId:"old",kind:"planning",label:"Planning Interview",now:"2026-05-06T09:00:00.000Z",expiresAt:"2026-05-06T09:01:00.000Z"});db.prepare(`INSERT INTO kit_agent_activity_leases (activity_id, agent_id, session_id, kind, label, started_at, updated_at, expires_at, details_json) VALUES (?,?,?,?,?,?,?,?,?)`).run("bad-json","copilot","bad-json","validating","Validating","2026-05-06T10:01:00.000Z","2026-05-06T10:01:00.000Z","2026-05-06T10:06:00.000Z","NOT JSON");assert.equal(listCurrentAgentActivityLeases(db,"2026-05-06T10:02:00.000Z").length,1);}finally{db.close();}});
