import type { TaskEntity, TaskStatus } from "./types.js";

const STATUS_MARKERS: Record<TaskStatus, string> = {
  proposed: "[p]",
  ready: "[ ]",
  in_progress: "[~]",
  blocked: "[!]",
  completed: "[x]",
  cancelled: "[-]"
};

function groupByPhase(tasks: TaskEntity[]): Map<string, TaskEntity[]> {
  const groups = new Map<string, TaskEntity[]>();
  for (const task of tasks) {
    const phase = task.phase ?? "Uncategorized";
    const group = groups.get(phase) ?? [];
    group.push(task);
    groups.set(phase, group);
  }
  return groups;
}

function buildReadyQueueLine(tasks: TaskEntity[]): string {
  const ready = tasks
    .filter((t) => t.status === "ready")
    .sort((a, b) => {
      const pa = a.priority ?? "P9";
      const pb = b.priority ?? "P9";
      return pa.localeCompare(pb);
    });

  if (ready.length === 0) return "- Ready queue: _(empty)_";
  return `- Ready queue: ${ready.map((t) => `\`${t.id}\``).join(", ")}`;
}

function buildCurrentPhase(tasks: TaskEntity[]): string {
  const inProgress = tasks.filter((t) => t.status === "in_progress");
  const ready = tasks.filter((t) => t.status === "ready");

  const active = [...inProgress, ...ready];
  if (active.length === 0) return "- Current phase in execution: _(no active tasks)_";

  const phases = [...new Set(active.map((t) => t.phase).filter(Boolean))];
  if (phases.length === 0) return "- Current phase in execution: _(unknown)_";

  return `- Current phase in execution: _${phases[0]}_`;
}

function renderTask(task: TaskEntity): string {
  const marker = STATUS_MARKERS[task.status] ?? "[ ]";
  const lines: string[] = [];

  lines.push(`### ${marker} ${task.id} ${task.title}`);

  if (task.priority) {
    lines.push(`- Priority: ${task.priority}`);
  }
  if (task.approach) {
    lines.push(`- Approach: ${task.approach}`);
  }

  const deps = task.dependsOn ?? [];
  lines.push(`- Depends on: ${deps.length > 0 ? deps.map((d) => `\`${d}\``).join(", ") : "none"}`);

  const unblocks = task.unblocks ?? [];
  if (unblocks.length > 0) {
    lines.push(`- Unblocks: ${unblocks.map((u) => `\`${u}\``).join(", ")}`);
  }

  if (task.technicalScope && task.technicalScope.length > 0) {
    lines.push("- Technical scope:");
    for (const item of task.technicalScope) {
      lines.push(`  - ${item}`);
    }
  }

  if (task.acceptanceCriteria && task.acceptanceCriteria.length > 0) {
    lines.push("- Acceptance criteria:");
    for (const item of task.acceptanceCriteria) {
      lines.push(`  - ${item}`);
    }
  }

  return lines.join("\n");
}

export function generateTasksMd(tasks: TaskEntity[]): string {
  const lines: string[] = [];

  lines.push("# Workflow Cannon Tasks");
  lines.push("");
  lines.push("> This file is generated by the Task Engine. Do not edit manually.");
  lines.push("");
  lines.push("Status markers:");
  lines.push("- `[p]` proposed");
  lines.push("- `[ ]` ready");
  lines.push("- `[~]` in progress");
  lines.push("- `[!]` blocked");
  lines.push("- `[x]` completed");
  lines.push("- `[-]` cancelled");
  lines.push("");

  lines.push("## Current execution state");
  lines.push("");
  lines.push(buildCurrentPhase(tasks));
  lines.push(buildReadyQueueLine(tasks));
  lines.push("");

  const phaseGroups = groupByPhase(tasks);
  for (const [phase, phaseTasks] of phaseGroups) {
    lines.push(`## ${phase}`);
    lines.push("");
    for (const task of phaseTasks) {
      lines.push(renderTask(task));
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function syncTaskHeadingsInMarkdown(markdown: string, tasks: TaskEntity[]): string {
  const byId = new Map(tasks.map((task) => [task.id, task]));
  const lines = markdown.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const match = line.match(/^###\s+\[[^\]]*\]\s+(T\d+)\s+(.+)$/);
    if (!match) continue;

    const id = match[1];
    const task = byId.get(id);
    if (!task) continue;

    const marker = STATUS_MARKERS[task.status] ?? "[ ]";
    lines[i] = `### ${marker} ${task.id} ${task.title}`;
  }

  return lines.join("\n");
}
