import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  allowedPackageManagers,
  currentOwnedPaths,
  pointerRuleContent,
  profileSchemaContent
} from "./profile-baseline-content.js";
import { CANONICAL_KIT_NAME, defaultWorkspaceKitPaths } from "./default-workspace-kit-paths.js";

export type WorkspaceKitProfile = {
  project: { name: string };
  packageManager: "pnpm" | "npm" | "yarn";
  commands: {
    test: string;
    lint: string;
    typecheck: string;
  };
  github: {
    defaultBranch: string;
  };
};

type OwnedPathsDocument = {
  schemaVersion: number;
  ownedPaths: string[];
  notes?: string;
};

export async function parseJsonFile(filePath: string): Promise<unknown> {
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw);
}

function readStringField(
  objectValue: Record<string, unknown>,
  key: string,
  errors: string[],
  fieldPath: string
): string | undefined {
  const value = objectValue[key];
  if (typeof value !== "string" || value.trim().length === 0) {
    errors.push(`${fieldPath} must be a non-empty string`);
    return undefined;
  }

  return value;
}

export async function validateProfile(
  cwd: string
): Promise<{ errors: string[]; profile?: WorkspaceKitProfile }> {
  const profilePath = path.join(cwd, defaultWorkspaceKitPaths.profile);
  const errors: string[] = [];
  let profile: unknown;

  try {
    profile = await parseJsonFile(profilePath);
  } catch {
    return { errors: [`${defaultWorkspaceKitPaths.profile} is missing or invalid JSON`] };
  }

  if (!profile || typeof profile !== "object" || Array.isArray(profile)) {
    return { errors: ["workspace-kit profile root must be an object"] };
  }

  const profileObject = profile as Record<string, unknown>;
  const project = profileObject.project;
  const commands = profileObject.commands;
  const github = profileObject.github;
  const packageManager = profileObject.packageManager;

  if (!project || typeof project !== "object" || Array.isArray(project)) {
    errors.push("project must be an object");
  } else {
    readStringField(project as Record<string, unknown>, "name", errors, "project.name");
  }

  if (typeof packageManager !== "string" || !allowedPackageManagers.has(packageManager)) {
    errors.push("packageManager must be one of: pnpm, npm, yarn");
  }

  if (!commands || typeof commands !== "object" || Array.isArray(commands)) {
    errors.push("commands must be an object");
  } else {
    const commandsObject = commands as Record<string, unknown>;
    readStringField(commandsObject, "test", errors, "commands.test");
    readStringField(commandsObject, "lint", errors, "commands.lint");
    readStringField(commandsObject, "typecheck", errors, "commands.typecheck");
  }

  if (!github || typeof github !== "object" || Array.isArray(github)) {
    errors.push("github must be an object");
  } else {
    readStringField(
      github as Record<string, unknown>,
      "defaultBranch",
      errors,
      "github.defaultBranch"
    );
  }

  if (errors.length > 0) {
    return { errors };
  }

  const validatedProject = profileObject.project as Record<string, unknown>;
  const validatedCommands = profileObject.commands as Record<string, unknown>;
  const validatedGithub = profileObject.github as Record<string, unknown>;
  const validatedPackageManager =
    profileObject.packageManager as WorkspaceKitProfile["packageManager"];

  return {
    errors,
    profile: {
      project: { name: validatedProject.name as string },
      packageManager: validatedPackageManager,
      commands: {
        test: validatedCommands.test as string,
        lint: validatedCommands.lint as string,
        typecheck: validatedCommands.typecheck as string
      },
      github: {
        defaultBranch: validatedGithub.defaultBranch as string
      }
    }
  };
}

export function toJsonWithTrailingNewline(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderProfileDrivenArtifacts(profile: WorkspaceKitProfile): {
  generatedContextJson: string;
  generatedRuleText: string;
} {
  const generatedContext = {
    generatedFrom: defaultWorkspaceKitPaths.profile,
    projectName: profile.project.name,
    packageManager: profile.packageManager,
    commands: profile.commands,
    github: profile.github
  };

  const generatedRuleText = [
    "# Workspace Kit Project Context (Generated)",
    "",
    "This file is generated by `workspace-kit init`.",
    "Do not hand-edit project identity values here; update `workspace-kit.profile.json` and rerun init.",
    "",
    `- project_name: ${profile.project.name}`,
    `- package_manager: ${profile.packageManager}`,
    `- default_branch: ${profile.github.defaultBranch}`,
    `- test_command: ${profile.commands.test}`,
    `- lint_command: ${profile.commands.lint}`,
    `- typecheck_command: ${profile.commands.typecheck}`,
    "",
    "When instructions need project-specific values, prefer this generated file or `.workspace-kit/generated/project-context.json`."
  ].join("\n");

  return {
    generatedContextJson: toJsonWithTrailingNewline(generatedContext),
    generatedRuleText: `${generatedRuleText}\n`
  };
}

export async function generateProfileDrivenArtifacts(
  cwd: string,
  profile: WorkspaceKitProfile
): Promise<{ generatedJsonPath: string; generatedRulePath: string }> {
  const generatedJsonPath = path.join(cwd, ".workspace-kit", "generated", "project-context.json");
  const generatedRulePath = path.join(cwd, ".cursor", "rules", "workspace-kit-project-context.mdc");
  const renderedArtifacts = renderProfileDrivenArtifacts(profile);

  await fs.mkdir(path.dirname(generatedJsonPath), { recursive: true });
  await fs.writeFile(generatedJsonPath, renderedArtifacts.generatedContextJson, "utf8");

  await fs.mkdir(path.dirname(generatedRulePath), { recursive: true });
  await fs.writeFile(generatedRulePath, renderedArtifacts.generatedRuleText, "utf8");

  return { generatedJsonPath, generatedRulePath };
}

export function createDriftExpectedAssets(profile: WorkspaceKitProfile): Map<string, string> {
  const generated = renderProfileDrivenArtifacts(profile);
  return new Map<string, string>([
    [defaultWorkspaceKitPaths.profileSchema, toJsonWithTrailingNewline(profileSchemaContent)],
    [".cursor/rules/workspace-kit-profile-pointer.mdc", pointerRuleContent],
    [".workspace-kit/generated/project-context.json", generated.generatedContextJson],
    [".cursor/rules/workspace-kit-project-context.mdc", generated.generatedRuleText]
  ]);
}

export function driftContentMatches(
  relativePath: string,
  existingContent: string,
  expectedContent: string
): boolean {
  if (!relativePath.endsWith(".json")) {
    return existingContent === expectedContent;
  }

  try {
    const existingJson = JSON.parse(existingContent);
    const expectedJson = JSON.parse(expectedContent);
    return JSON.stringify(existingJson) === JSON.stringify(expectedJson);
  } catch {
    return existingContent === expectedContent;
  }
}

export async function resolvePackageVersion(cwd: string): Promise<string | undefined> {
  const candidatePaths = [
    path.join(cwd, "packages", "workspace-kit", "package.json"),
    path.join(cwd, "package.json")
  ];

  for (const candidatePath of candidatePaths) {
    try {
      const parsed = await parseJsonFile(candidatePath);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const version = (parsed as Record<string, unknown>).version;
        const name = (parsed as Record<string, unknown>).name;
        if (typeof version === "string" && version.length > 0 && typeof name === "string") {
          if (
            name === CANONICAL_KIT_NAME ||
            name === "quicktask-workspace-kit" ||
            candidatePath.endsWith("packages/workspace-kit/package.json")
          ) {
            return version;
          }
        }
      }
    } catch {
      continue;
    }
  }

  return undefined;
}

/** Version from the installed kit package (works from repo `dist/` or `node_modules`). */
export async function readCliBundledPackageVersion(): Promise<string | undefined> {
  try {
    const pkgPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "package.json");
    const parsed = await parseJsonFile(pkgPath);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const v = (parsed as Record<string, unknown>).version;
      return typeof v === "string" && v.length > 0 ? v : undefined;
    }
  } catch {
    /* ignore */
  }
  return undefined;
}

export async function readOwnedPathsDocument(cwd: string): Promise<OwnedPathsDocument> {
  const ownedPathsPath = path.join(cwd, defaultWorkspaceKitPaths.ownedPaths);
  let parsed: unknown;

  try {
    parsed = await parseJsonFile(ownedPathsPath);
  } catch {
    return {
      schemaVersion: 1,
      ownedPaths: currentOwnedPaths,
      notes: "Owned path policy fallback generated by workspace-kit upgrade."
    };
  }

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return {
      schemaVersion: 1,
      ownedPaths: currentOwnedPaths,
      notes: "Owned path policy fallback generated by workspace-kit upgrade."
    };
  }

  const value = parsed as Record<string, unknown>;
  const ownedPaths = Array.isArray(value.ownedPaths)
    ? value.ownedPaths.filter((item): item is string => typeof item === "string")
    : [];

  return {
    schemaVersion: typeof value.schemaVersion === "number" ? value.schemaVersion : 1,
    ownedPaths: ownedPaths.length > 0 ? ownedPaths : currentOwnedPaths,
    notes: typeof value.notes === "string" ? value.notes : undefined
  };
}

export async function writeFileWithBackupIfChanged(
  cwd: string,
  relativePath: string,
  content: string,
  backupRoot: string
): Promise<boolean> {
  const targetPath = path.join(cwd, relativePath);
  let existingContent: string | undefined;

  try {
    existingContent = await fs.readFile(targetPath, "utf8");
  } catch {
    existingContent = undefined;
  }

  if (existingContent === content) {
    return false;
  }

  if (typeof existingContent === "string") {
    const backupPath = path.join(backupRoot, `${relativePath}.bak`);
    await fs.mkdir(path.dirname(backupPath), { recursive: true });
    await fs.writeFile(backupPath, existingContent, "utf8");
  }

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, content, "utf8");
  return true;
}
