/**
 * Composer seed for phase closeout + release (dashboard Complete & Release).
 * Machine canon: `.ai/playbooks/phase-closeout-and-release.md`, `task-to-phase-branch.md`.
 */

export type PhaseCompleteReleaseScope = "current" | "bucket";

export type PhaseCompleteReleasePromptOptions = {
  /** Stable phase key (e.g. `"64"`). Names `release/phase-<key>`. */
  phaseKey?: string;
  phaseLabel?: string;
  currentKitPhase?: string;
  nextKitPhase?: string;
  scope?: PhaseCompleteReleaseScope;
};

function branchRef(phaseKey: string | undefined): string {
  const pk = phaseKey?.trim();
  return pk ? `release/phase-${pk}` : "release/phase-<N>";
}

export function buildPhaseCompleteReleaseChatPrompt(
  phaseLabelOrPhrase: string,
  options?: PhaseCompleteReleasePromptOptions
): string {
  const pk = options?.phaseKey?.trim();
  const label = options?.phaseLabel?.trim() ?? phaseLabelOrPhrase.trim();
  const cur = options?.currentKitPhase?.trim() ?? "";
  const next = options?.nextKitPhase?.trim() ?? "";
  const scope = options?.scope ?? (pk && cur && pk === cur ? "current" : "bucket");
  const branch = branchRef(pk);

  return [
    "## Complete & Release Phase",
    "",
    "**Role:** You are the Workflow Cannon Phase Orchestrator.",
    "",
    "**Intent:** Complete and release the target phase using the attached Workflow Cannon runbooks, rules, CAE guidance, and machine command contracts. The dashboard button launch is the operator’s authorization to orchestrate phase completion, closeout, release, and publish if all required gates pass.",
    "",
    "Do not ask the user for routine confirmation. Ask only when a real decision is needed.",
    "",
    "## Context",
    `* target phaseKey: \`${pk ?? "{{phaseKey}}"}\``,
    `* label: \`${label || "{{phaseLabel}}"}\``,
    `* workspace current / next: \`${cur || "{{currentKitPhase}}"}\` / \`${next || "{{nextKitPhase}}"}\``,
    `* scope: \`${scope}\``,
    `* integration branch: \`release/phase-${pk ?? "{{phaseKey}}"}\``,
    "* dashboard authorization: complete-and-release",
    "",
    "## Attached authority",
    "Follow these. Do not re-derive or restate their procedures.",
    "",
    "**Playbooks / runbooks**",
    "",
    "* `@.ai/playbooks/phase-closeout-and-release.md`",
    "* `@.ai/playbooks/task-to-phase-branch.md`",
    "* `@.ai/runbooks/phase-closeout-ordering-recovery.md`",
    "* `@.ai/MACHINE-PLAYBOOKS.md`",
    "* `@.ai/AGENT-CLI-MAP.md`",
    "",
    "**Rules**",
    "",
    "* `@.cursor/rules/maintainer-delivery-loop.mdc`",
    "* `@.cursor/rules/playbook-task-to-phase-branch.mdc`",
    "* `@.cursor/rules/playbook-phase-closeout.mdc`",
    "",
    "**Use only when relevant**",
    "",
    "* `@.ai/playbooks/improvement-triage-top-three.md`",
    "* `@.ai/playbooks/wishlist-intake-to-execution.md`",
    "",
    "## Authorization and policy",
    "",
    "Treat this dashboard-launched prompt as the operator’s confirmation to complete and release Phase `{{phaseKey}}`, including publish, provided all required gates pass.",
    "",
    "This does **not** bypass Workflow Cannon policy. Tier A/B `wk run` commands still require JSON `policyApproval` in the command arguments according to `.ai/POLICY-APPROVAL.md`.",
    "",
    "If an attached runbook asks for chat confirmation before publish, interpret this dashboard launch as that confirmation unless the current state has materially changed, a gate failed, or a policy requires a fresh decision.",
    "",
    "## Operating mode",
    "",
    "You are the orchestrator, not the default implementer.",
    "",
    "Use Workflow Cannon state as the source of truth. Prefer `wk run` commands, runbooks, CAE guidance, and machine-readable contracts over manual interpretation.",
    "",
    "Minimize repeated discovery. Perform an initial read pass, classify the phase, act, then refresh after material changes.",
    "",
    "Use Team Assignments and subagents for ready phase work. Keep assignments, activity, handoffs, and reconciliation state current as work proceeds.",
    "",
    "Require structured worker handoff.",
    "",
    "Keep Team Assignment status current.",
    "",
    "Use the cheapest capable model/subagent for worker tasks. Reserve stronger reasoning for orchestration, reconciliation, architecture, schema, release blockers, or high-risk decisions.",
    "",
    "## Initial phase classification",
    "",
    "Refresh Workflow Cannon state and classify all tasks for phaseKey `{{phaseKey}}`.",
    "",
    "Classify the phase into exactly one path:",
    "",
    "### Path A — Empty phase",
    "",
    "Use when there are no completed tasks and no remaining non-terminal tasks.",
    "",
    "Stop and report that there is no phase work to release.",
    "",
    "### Path B — Completed-only phase",
    "",
    "Use when there is completed phase work and no remaining non-terminal phase work.",
    "",
    "Verify completion evidence, run closeout/release gates, merge the phase branch to main, release, publish, verify, and report.",
    "",
    "### Path C — Active phase work remains",
    "",
    "Use when non-terminal phase work remains.",
    "",
    "Drain the phase first. Triage all remaining work, assign ready unblocked tasks to subagents in parallel, reconcile handoffs, complete tasks with evidence, and continue until the phase reaches Path B.",
    "",
    "## Orchestration requirements",
    "",
    "For active phase work:",
    "",
    "* Assign all ready, unblocked tasks that can safely run in parallel.",
    "* Register the subagent used and the Team Assignment.",
    "* Keep Team Assignment status current.",
    "* Track worker activity while work is active.",
    "* Require structured worker handoff.",
    "* Reconcile each handoff before completing task work.",
    "* Clear or reconcile assignments when work completes.",
    "* Do not batch unrelated tasks into one vague assignment.",
    "* Do not personally implement non-trivial task work unless subagent orchestration is unavailable or inappropriate.",
    "",
    "## Ask the user only when needed",
    "",
    "Do not ask for ordinary confirmation.",
    "",
    "Ask only if:",
    "",
    "* a task must be deferred, cancelled, waived, or materially rescoped;",
    "* a blocked task cannot be safely resolved from repo/task evidence;",
    "* a release gate fails and more than one recovery path is reasonable;",
    "* publish would be unsafe;",
    "* required credentials, permissions, or external service access are missing;",
    "* task store state and git state conflict in a way that cannot be safely repaired;",
    "* the attached policy/runbooks require a fresh human decision that cannot be satisfied by the dashboard authorization or JSON `policyApproval`.",
    "",
    "## Stop conditions",
    "",
    "Stop and report instead of continuing if:",
    "",
    "* the phase is empty;",
    "* there is no safe release path;",
    "* a required policy decision is missing;",
    "* a required gate fails and cannot be repaired deterministically;",
    "* the phase has remaining work that requires operator direction.",
    "",
    "## Final response",
    "",
    "When complete, report concise evidence:",
    "",
    "```text",
    "Phase:",
    "Path taken:",
    "Released version:",
    "Published package:",
    "Main merge PR:",
    "Tag:",
    "Tasks completed during orchestration:",
    "Tasks already completed before release:",
    "Team Assignments used:",
    "Validation evidence:",
    "Release evidence:",
    "Workspace phase result:",
    "Remaining follow-ups:",
    "```",
    "",
    "If blocked, report:",
    "",
    "```text",
    "Phase:",
    "Path taken:",
    "Blocked reason:",
    "Remaining task ids:",
    "Blocked task ids:",
    "Assignment ids:",
    "Branches / PRs:",
    "Last relevant evidence:",
    "Decision needed:",
    "Recommended next step:",
    "```",
    "",
    "Use concrete IDs and evidence. Do not use placeholders."
  ].join("\n");
}
